services:
  api:
    build:
      context: ./
    networks: 
      - route_network
    volumes:
      - ./file-storage:/home/node/app1/file-storage
      - ./logs:/home/node/app1/pmsv2-services/logs
    container_name: running-pmsv2-services
    restart: always
    env_file:
      - .env.prod

networks:
  route_network:
    external: true
