services:
  api:
    build:
      context: ./
    networks: 
      - route_network
    volumes:
      - ./file-storage:/home/node/app1/file-storage
      - ./logs:/home/node/app1/pms-v2-service/logs
    container_name: running-pms-v2-service
    restart: always

networks:
  route_network:
    external: true
