export enum RETURN_MESSAGE {
  CREATE_SUCCESS = 'Created is success',
  CREATE_FAIL = 'Created is fail',
  SUCCESS = 'Process is success',
  FAIL = 'Process is fail',
  LOGIN_SUCCESS = 'Login is success',
  LOGIN_FAIL = 'Login is fail',
  REGISTER_SUCCESS = 'Register is success',
  REGISTER_FAIL = 'Register is fail',
  FORGET_PASSWORD_SUCCESS = 'Forget password is success',
  FORGET_PASSWORD_FAIL = 'Forget password is fail',
  RESET_PASSWORD_SUCCESS = 'Reset password is success',
  RESET_PASSWORD_FAIL = 'Reset password is fail',
  USER_NOT_ACTIVE = 'User is not active',
  USER_NOT_FOUND = 'User is not found',
  INVALID_TOKEN = 'Invalid token',
  DELETE_SUCCESS = 'Delete is success',
  DELETE_FAIL = 'Delete is fail',
  NOT_FOUND = 'Not found',
  INVALID_CRIDENTIAL = 'Invalid cridential',
  USER_ROLE_MENU_EXIST = 'User role menu is exist',
}
